### ISSUE TITLE
Postgresql password should be moved into an environment variable

### ISSUE THREAD

**Issue by abukosek** [oasisprotocol/oasis-web3-gateway#1]
Currently, the postgresql password is stored in plaintext in the config file (`conf/server.yml`).

It should be moved into an environment variable (and the username into its own environment variable as well).

**Comment by SzeChuanChilliSauce** [comment]
we moved db user and pwd into env vars in #44.

**Comment by ptrus** [comment]
With https://github.com/starfishlabs/oasis-evm-web3-gateway/pull/68 all configuration vars can also be set via ENV. Specifically for the Postgress password the `DATABSE__PASSWORD` env var can be used.
