### ISSUE TITLE
Hardcoded block gas limit in block headers is incorrect

### ISSUE THREAD

**Issue by peterjgilbert** [oasisprotocol/oasis-web3-gateway#151]
The block gas limit is hardcoded to 21,000,000 in returned block headers. This value is incorrect.

https://github.com/oasisprotocol/emerald-web3-gateway/blob/50a5aefa81c2f9f8f3e5b2c4f8e0cec98d896ea2/indexer/utils.go#L88

**Comment by kostko** [comment]
Yeah this should actually query the runtime parameters and use that. Note sure if the runtime currently exposes that query though, but it should be an otherwise non-breaking change.
