### ISSUE TITLE
Indexer: Ignore duplicated failed transactions 

### ISSUE THREAD

**Issue by ptrus** [oasisprotocol/oasis-web3-gateway#152]
Gateway should ignore duplicate (failed) transactions. In the emerald paratime it can happen that an already committed transaction is re-proposed at a later block. The duplicate transaction fails, but it is still included in the block. The web3-gateway should drop these transactions to remain compatible with eth semantics.

For failed transactions this upsert should be chaged into "insert if not exists":
https://github.com/oasisprotocol/emerald-web3-gateway/blob/0b703ceda7419e2982abd6d42e5a925916a05598/indexer/utils.go#L263-L266

**Comment by peterjgilbert** [comment]
It should also exclude these transactions when it computes the gas used and log filter for the block.

**Comment by peterjgilbert** [comment]
> For failed transactions this upsert should be chaged into "insert if not exists":

Capturing the reasoning here: this approach is safe because the indexer processes blocks in order.
