### ISSUE TITLE
Compatible with new core oasis?

### ISSUE THREAD

**Issue by antony-everstake** [oasisprotocol/oasis-web3-gateway#159]
There is a new version [oasis core v21.3.8](https://github.com/oasisprotocol/oasis-core/releases/tag/v21.3.8).
Is Emerald Web3 Gateway 1.1.0 compatible with [oasis core v21.3.8](https://github.com/oasisprotocol/oasis-core/releases/tag/v21.3.8)?

**Comment by matevz** [comment]
Yes, this was bumped in https://github.com/oasisprotocol/emerald-web3-gateway/pull/158 and https://github.com/oasisprotocol/emerald-web3-gateway/pull/165

**Comment by ptrus** [comment]
And yes, Emerald Web3 Gateway 1.1.0 is ao compatible with oasis core v21.3.8.
