### ISSUE TITLE
Build and deploy emerald-dev docker image on pushes to main

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/oasis-web3-gateway#169]
Bump, rebuild and deploy the emerald-dev docker image introduced in #168 to dockerhub at least on each:
- new oasis-core release
- new emerald-paratime release
- new web3-gateway release

Perhaps we should also consider `next` version of the image using `main` branches of the components?

**Comment by ptrus** [comment]
I think the emerald-dev image should only be build on web3-gateway merges to main. 

Web3 gateway always depends on specific emerald-paratime and oasis-core versions. It's good enough to build the image when the dependencies in this repository are updated.

**Comment by matevz** [comment]
Let's simplify things. PR #175 verions the emerald-dev image as Y-m-d-gitcommit and on each push to main the new docker image is deployed as `latest`.
