### ISSUE TITLE
failed to prune round

### ISSUE THREAD

**Issue by maiquanghiep** [oasisprotocol/oasis-web3-gateway#200]
##### SUMMARY
I'm trying to use the prune option in gateway.yml. While the indexer is working fine, the prune returns timeout error.

`
Mar 03 03:33:08 oasis-m-emerald-paratime-ln-atl oasis-evm-web3-gateway[2510391]: {"caller":"json_rpc.go:126","cors":"","endpoint":"[::]:8545","level":"info","module":"gateway","msg":"HTTP server started","prefix":"","provided_endpoint":"0.0.0.0:8545","server":"http","ts":"2022-03-03T03:33:08.232304243Z"}
Mar 03 03:33:08 oasis-m-emerald-paratime-ln-atl oasis-evm-web3-gateway[2510391]: {"caller":"json_rpc.go:126","cors":"","endpoint":"[::]:8546","level":"info","module":"gateway","msg":"HTTP server started","prefix":"","provided_endpoint":"0.0.0.0:8546","server":"ws","ts":"2022-03-03T03:33:08.232384054Z"}
Mar 03 03:33:12 oasis-m-emerald-paratime-ln-atl oasis-evm-web3-gateway[2510391]: {"caller":"backend.go:112","level":"info","module":"indexer","msg":"indexed block","round":633475,"ts":"2022-03-03T03:33:12.171326575Z"}
Mar 03 03:34:05 oasis-m-emerald-paratime-ln-atl oasis-evm-web3-gateway[2510391]: {"caller":"backend.go:112","level":"info","module":"indexer","msg":"indexed block","round":633476,"ts":"2022-03-03T03:34:05.173315289Z"}
Mar 03 03:34:18 oasis-m-emerald-paratime-ln-atl oasis-evm-web3-gateway[2510391]: {"caller":"indexer.go:155","err":"read tcp [::1]:45394->[::1]:5432: i/o timeout","level":"error","module":"gateway/indexer","msg":"failed to prune round","round":533476,"runtime_id":"000000000000000000000000000000000000000000000000e2eaa99fc008f87f","ts":"2022-03-03T03:34:18.423058356Z"}
Mar 03 03:34:52 oasis-m-emerald-paratime-ln-atl oasis-evm-web3-gateway[2510391]: {"caller":"backend.go:112","level":"info","module":"indexer","msg":"indexed block","round":633477,"ts":"2022-03-03T03:34:52.679160127Z"}
Mar 03 03:35:28 oasis-m-emerald-paratime-ln-atl oasis-evm-web3-gateway[2510391]: {"caller":"indexer.go:155","err":"read tcp [::1]:45558->[::1]:5432: i/o timeout","level":"error","module":"gateway/indexer","msg":"failed to prune round","round":533477,"runtime_id":"000000000000000000000000000000000000000000000000e2eaa99fc008f87f","ts":"2022-03-03T03:35:28.504218235Z"}
Mar 03 03:35:33 oasis-m-emerald-paratime-ln-atl oasis-evm-web3-gateway[2510391]: {"caller":"backend.go:112","level":"info","module":"indexer","msg":"indexed block","round":633478,"ts":"2022-03-03T03:35:33.511597642Z"
`

**Comment by ptrus** [comment]
This looks like the prune transaction is timing out: https://github.com/oasisprotocol/emerald-web3-gateway/blob/607b8e4d8a881097265c1e4beafe02d1490ff96d/indexer/backend.go#L115-L135

You might want to try increasing the database timeouts here: https://github.com/oasisprotocol/emerald-web3-gateway/blob/28e90f64637e3e36624f673ae1f5130d6584809e/conf/tests.yml#L14-L16

You might also want to check the load on the postgresql database and potentially scale up the database resources.

**Comment by ptrus** [comment]
Hi, additionally to increasing the timeouts, the pruning should be sped up with new releases that include: https://github.com/oasisprotocol/emerald-web3-gateway/issues/227
