### ISSUE TITLE
Add tests for Docker images

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/oasis-web3-gateway#215]
Currently, the emerald-dev and sapphire-dev images are only built on each push to main, so it can actually break without developer noticing it. Also, even if the image is successfully built, the image might not work (e.g. #214).

Add at least two tests before any PR can be merged:
- [ ] check that the docker images would be successfully built
- [ ] check that the docker images actually start and (at least) successfully populate the accounts (just check the stdout for some `0x` addresses?)

Typical issues with images include wrong combination of oasis-core/xyz-paratime/web3-gw versions and oasis-node/web3-gw configuration issues.

**Comment by ptrus** [comment]
This has been implemented in https://github.com/oasisprotocol/oasis-web3-gateway/pull/469
