### ISSUE TITLE
Bump emerald-dev image to oasis-node to 22.1+

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/oasis-web3-gateway#250]
Bump to oasis-core to at least 22.1and emerald-paratime 8.0.0-testnet. This requires adding `--debug.allow_root` flag to oasis-node to avoid the new EUID bit checks. It seems there's also some other issues with the bump.

**Comment by ptrus** [comment]
Done in https://github.com/oasisprotocol/emerald-web3-gateway/pull/290 & https://github.com/oasisprotocol/emerald-web3-gateway/pull/292
