### ISSUE TITLE
Add end-to-end tests

### ISSUE THREAD

**Issue by abukosek** [oasisprotocol/oasis-web3-gateway#3]
End-to-end tests should be added.

Run `oasis-net-runner`, `pgsqld`, and the gateway, then issue requests to test the gateway's functionality.

**Comment by synote** [comment]
Basic tests are added in https://github.com/starfishlabs/oasis-evm-web3-gateway/tree/main/tests/rpc
There is also contract deploy tests which are from simpleevmtest

The tests work with a local evm-paratime loaded with oasis-net-runner

**Comment by kostko** [comment]
Would be great if these tests were also made to run as part of the CI workflow via GitHub actions.

**Comment by kostko** [comment]
This was done in #45.
