### ISSUE TITLE
go-pg/pg vs uptrace/bun

### ISSUE THREAD

**Issue by bennetyee** [oasisprotocol/oasis-web3-gateway#35]
we are using go-pg/pg

https://github.com/starfishlabs/oasis-evm-web3-gateway/blob/e8fb482c4f855091c46ff263e9e289b02ee26847/storage/psql/psql.go#L9

but at https://github.com/go-pg/pg it seems to be in maintenance mode, deprecated for new code:

```
go-pg is in a maintenance mode and only critical issues are addressed. New development happens in Bun repo which offers similar functionality but works with PostgreSQL, MySQL, MariaDB, and SQLite.

https://github.com/uptrace/bun
```

bun is a rewrite of go-pg and the recommendation is that new code should prefer bun over go-pg, though there is no urgency in rewriting existing code (and that is not supposed to be difficult).  since this is new code, why aren't we using bun?

https://bun.uptrace.dev/guide/pg-migration.html

it feels like we are creating technical debt, since we know that in the near(-ish) future, we will have to update to bun.

**Comment by SzeChuanChilliSauce** [comment]
Thanks for your advice. We didn't know there was a better library. We'll replace it with bun.
