### ISSUE TITLE
db Insert error return ignored, not handled

### ISSUE THREAD

**Issue by bennetyee** [oasisprotocol/oasis-web3-gateway#38]
https://github.com/starfishlabs/oasis-evm-web3-gateway/blob/f6a1b3ce1622603f9f2226da63a6644a2891802c/indexer/backend.go#L187

ignores the potential error return from `p.storage.Store(blockRef)` -- this is possible, since

https://github.com/starfishlabs/oasis-evm-web3-gateway/blob/f6a1b3ce1622603f9f2226da63a6644a2891802c/storage/psql/psql.go#L73-L76
passes up the error return from `db.Db.Model(value).Insert()`.

instead, `Index` only ever returns `nil`.

the user of this is https://github.com/starfishlabs/oasis-evm-web3-gateway/blob/f6a1b3ce1622603f9f2226da63a6644a2891802c/indexer/indexer.go#L56

which would have returned `ErrIndexedFailed` if it ever got a non-`nil` status.  `indexBlock` is used from `indexingWorker()`, and errors cause the worker thread to sleep.  `indexBlock` returns two types of errors, the first from `s.client.GetBlock` or `s.client.GetTransaction` which are networking (grpc) issues that may be temporary.  the database error that _isn't_ currently returned is local and not a network problem, so it's unclear that sleeping is the right thing to do if/when the error propagation is plumbed through -- go-pg/pg seem to indicate that `Insert()` failures are panic-worthy, so maybe that's the right thing to do and require a wipe/rebuild of the db or restore from backup or something like that?  If a db corruption causes the `Insert()` to consistently fail, then the `nil` comparison in `indexingWorker` will live-lock, essentially just continuously loop sleeping and generating a misleading Warn log entry.

**Comment by SzeChuanChilliSauce** [comment]
Yes, there is really no need to use global variables. We will removed it.
