### ISSUE TITLE
getBlockNumber method not implemented

### ISSUE THREAD

**Issue by ptrus** [oasisprotocol/oasis-web3-gateway#4]
Looks like the method [`getBlockNumber`](https://web3js.readthedocs.io/en/v1.2.11/web3-eth.html#getblocknumber), which should return the current block, is missing.

Is this method not implemented or did I miss something?

> err="the method eth_blockNumber does not exist/is not available"

**Comment by anonymousGiga** [comment]
I add a method BlockNumber which you can test.

**Comment by ptrus** [comment]
Works, thanks!
