### ISSUE TITLE
sapphire-localnet: expose internal.sock

### ISSUE THREAD

**Issue by CedarMist** [oasisprotocol/oasis-web3-gateway#423]
This will allow Go client and Oasis CLI can connect from outside docker.

One option would be to do a bind-mount to expose the `client-0` directory:

    OASIS_NODE_SOCKET=${OASIS_NODE_DATADIR}/net-runner/network/client-0/internal.sock

Another cleaner option would be to expose over TCP.

Or, may be able to link two containers together and directly expose the socket from one to another?

**Comment by matevz** [comment]
Some reading https://docs.oasis.io/core/oasis-node/rpc

I think we use https://www.npmjs.com/package/envoy-node in production.

**Comment by matevz** [comment]
The following works, but it's not pretty, acrobatics with docker's permissions...

```shell
mkdir serverdir
docker run -it -p8545:8545 -p8546:8546 -v /home/user/serverdir:/serverdir ghcr.io/oasisprotocol/sapphire-dev
# wait for sapphire-dev to spin up

# fix permissions
sudo chmod a+x serverdir/node/net-runner
sudo chmod a+x serverdir/node/net-runner/network
sudo chmod a+x serverdir/node/net-runner/network/client-0
sudo chmod a+rwx serverdir/node/net-runner/network/client-0/internal.sock

# now we can use Oasis CLI on internal.sock, for example
oasis net add-local docker unix:/home/user/serverdir/node/net-runner/network/client-0/internal.sock
oasis pt add docker sapphire 8000000000000000000000000000000000000000000000000000000000000000
oasis acc show test:cory --network docker
```

Another useful thing is that the `serverdir` is persistent after Docker is closed, so you can examine logs etc. `oasis-net-runner` purges `serverdir` the next time you run it though.

**Comment by CedarMist** [comment]
Another way of doing it would be just adding the oasis-cli to the container, and having a shell script which either starts the node or executes oasis-cli within the current node?

That would avoid a lot of bind mounting weirdness and permissions, although wouldn't let you do development of the CLI against a sapphire-dev node.

Is there any reason we can't just connect over TCP? Then you can expose it via `-p`

**Comment by aefhm** [comment]
> adding the oasis-cli to the container

➕

**Comment by CedarMist** [comment]
I'm using bind mounts to expose the serverdir in `/tmp`:

`-v /tmp/eth-runtime-test:/serverdir/node`

This has been working well for me for a few months.

**Comment by aefhm** [comment]
Adding the requirement that this should ideally work for Mac as well.
