### ISSUE TITLE
Handle p.storage.* errors

### ISSUE THREAD

**Issue by nhynes** [oasisprotocol/oasis-web3-gateway#48]
* https://github.com/starfishlabs/oasis-evm-web3-gateway/blob/main/indexer/backend.go#L187
* https://github.com/starfishlabs/oasis-evm-web3-gateway/blob/main/indexer/backend.go#L203
* https://github.com/starfishlabs/oasis-evm-web3-gateway/blob/main/indexer/backend.go#L261

These errors are silently ignored, which will cause the containing functions to report success. At the every least, storage errors should be returned so that on-call engineers can diagnose storage system failures

**Comment by kostko** [comment]
Is this a duplicate of #38? Maybe these issued should be merged.
