### ISSUE TITLE
Implement some missing methods

### ISSUE THREAD

**Issue by ptrus** [oasisprotocol/oasis-web3-gateway#5]
The following methods (maybe some others as well, didn't check totally in depth) are currently not implemented by the gateway, as implementing those correctly probably doesn't make sense.

For compatibility reasons it might make sense handling these methods similarly as Infura does:
```
eth_accounts - Always returns empty account list
eth_getWork - returns an "no mining work available yet" error
eth_hashrate - always returns a 0x0 mining hash rate
eth_mining - always returns false in response to eth_mining
```
ref: https://infura.io/docs/ethereum/json-rpc

**Comment by synote** [comment]
Yes, there are more rpc methods which can be provided with empty implementation.
I'll try to add the rpc methods for web3 compatibility.

**Comment by ptrus** [comment]
This one is done i think, thanks!
