### ISSUE TITLE
eth_feeHistory not supported

### ISSUE THREAD

**Issue by CedarMist** [oasisprotocol/oasis-web3-gateway#501]
The `eth_feeHistory` and `eth_maxPriorityFeePerGas` JSON-RPC calls are used by Web3.py when estimating gas

**Comment by ptrus** [comment]
While this is technically possible to implement, one possibility is also to just require the usage of the `eth_gasPrice` endpoint. I believe this is easy to configure in web3.py by setting the [gas_price strategy](https://github.com/ethereum/web3.py/blob/8f853f5841fd62187bce0c9f17be75627104ca43/web3/gas_strategies/rpc.py#L14).

The reasoning for this is that the gas-price returned by the oasis-web3-gateway is dynamically calculated and it should be a good estimate ([see here for details](https://github.com/oasisprotocol/oasis-web3-gateway/blob/07081eb0c90ec91a3af3bc2082bc248d0a812cc0/gas/backend.go#L60-L71)). I believe this should generally return a good gas price value. Also note that the way [oasis-sdk handles EIP1559 transactions](https://github.com/oasisprotocol/oasis-sdk/blob/da9d86d52abca27930ec4e63c7735ca30f2f16b8/runtime-sdk/modules/evm/src/raw_tx.rs#L102-L105) base-fee is always zero.

Can you please comment on how high priority is adding the eth_feeHistory endpoint, or if is using eth_gasPrice an ok short-term solution?

---

As for implementation goes, seems somewhat straightforward with some caveats/simplification:

- we should limit the query only to recent blocks. E.g. web3-js implementation mentions: 
> Transaction fee history Returns base fee per gas and transaction effective priority fee per gas history for the requested block range if available. The range between headBlock-4 and headBlock is guaranteed to be available while retrieving data from the pending block and older history are optional to support.
 
  As per the above seems reasonable limiting to e.g. last 10 blocks.

- Don't support queries for blocks in the past (past the last 10 blocks) - seems no reason to need this for estimating gas price.

- The way [oasis-sdk hanldles EIP1559 transactions](https://github.com/oasisprotocol/oasis-sdk/blob/da9d86d52abca27930ec4e63c7735ca30f2f16b8/runtime-sdk/modules/evm/src/raw_tx.rs#L102-L105) BASEFEE is always zero.


So the implementation requires:
- fetch last X blocks and calculate the provided percentiles and block gas used ratios

**Comment by ptrus** [comment]
There's an initial implementation in https://github.com/oasisprotocol/oasis-web3-gateway/pull/502 Seems to be working based on the simple unit test. Needs some more testing.

Feel free to try it out if you'll have the time.
