### ISSUE TITLE
eth_gasPrice should be implemented 

### ISSUE THREAD

**Issue by ptrus** [oasisprotocol/oasis-web3-gateway#6]
Can probably return a a static/dummy value

**Comment by kostko** [comment]
Actually it could use the `core.MinGasPrice` query.

**Comment by synote** [comment]
There is `eth_gasPrice` in the latest version:
https://github.com/starfishlabs/oasis-evm-web3-gateway/blob/825d855ab35ce813f744dab66cd78021fe1cb84c/rpc/eth/api.go#L175

The test https://github.com/starfishlabs/oasis-evm-web3-gateway/blob/825d855ab35ce813f744dab66cd78021fe1cb84c/tests/rpc/rpc_test.go#L117 with local network return gas price of 0.
I wonder if the zero gasPrice will be a problem in real network.

**Comment by kostko** [comment]
The actual minimum price is part of the runtime module parameters and can be changed through governance. Of course compute nodes can locally decide to not include your transactions if the price is too low (even if the minimum is zero).

**Comment by ptrus** [comment]
I think this one is done
