### ISSUE TITLE
Broken query in getTransactionByHash?

### ISSUE THREAD

**Issue by ptrus** [oasisprotocol/oasis-web3-gateway#7]
I get the following error while querying a transaction by hash:
```
curl http://localhost:8545 \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_getTransactionByHash","params": ["0xa0dc2a0dd95c6f8d08726b958292373a94f85a7ebd50ba22cca342fa11e13bc2"],"id":1}' 
 
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"ERROR #42P01 missing FROM-clause entry for table \"eth_transaction\""}}
```

Looks like the `getTransactionByHash` does an invalid query that fails.

**Comment by kostko** [comment]
Also it would be good that internal errors like these would not leak via RPC but only be logged in the gateway's log.

The method should return something like _"Internal error"_ instead if it encounters an unexpected error and log the actual error.

**Comment by ptrus** [comment]
Thanks, one more thing. Querying a non-existing transaction by hash now returns the following error:
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"pg: no rows in result set"}}
```

The message should probably be changed to something like: "transaction not found".  Same for any other errors for other methods, it would be great if internal errors would not leak in responses (as Jernej mentioned above already).

**Comment by ptrus** [comment]
works thanks
