### ISSUE TITLE
(Potentially) Use ethereum compatible block hashes computed from block headers

### ISSUE THREAD

**Issue by ptrus** [oasisprotocol/oasis-web3-gateway#72]
Apparently some clients ([go-ethereum](https://github.com/ethereum/go-ethereum/blob/33f28138095faada5cbf027849993808a9dba785/core/types/block.go#L374-L383)) compute block hashes from the ETH headers "on-the-fly" and don't use the `hash` value that is returned in the response of the WEB3 `getBlockBy*` calls. 

For example, the following code (using `go-ethereum`) does not work with the web3-gateway:
```golang
	blk1, err := ec.BlockByNumber(ctx, number)
	require.NoError(t, err)

	// blk1.Hash() is computed on the fly and does not match the oasis-evm-web3 notion of the block hash.
	blk2, err := ec.BlockByHash(ctx, blk1.Hash()) 
	require.NoError(t, err)
```

Oasis-evm-web3-gateway currently uses Oasis Runtime Block Hashes as the "Ethereum Block Hashes", therefore there is no way for the client to compute the same hash by itself from the directly from the Ethereum Header. The gateway and the indexer could be switched to instead use the hashes computed from "ethereum" transactions. 

The only downside (that I see) with this is: web3 block hashes would not match the runtime block hashes anymore. However if this mapping is ever needed, the corresponding runtime block hash can always be obtained by using the block number.

TODO:
- check if this is commonly done in other similar projects
  - [x] Avalnche C-Chain has same "problem"
  - [x] Moonbeam (Polkadot EVM compatible parachain) has the same "problem"  
- check if other ethereum clients also compute the hashes locally or use the hashes obtained in the API response (e.g. web3-js doesn't have this problem)
  - [x] `go-ethereum` computes hashes locally
  - [x] `web3js` doesn't compute hashes locally 
- would there be any potential downsides with this approach?

NOTE: This would be major breaking change on how blocks are indexed and any existing web3 deployments would either need to be re-indexed or migrated.

This change should not be done before other bigger refactorings are finished (https://github.com/starfishlabs/oasis-evm-web3-gateway/pull/45 https://github.com/starfishlabs/oasis-evm-web3-gateway/pull/44)

---

Since this problem seems specific to `go-ethereum` (as other clients seem not to compute hashes locally) this probably won't be fixed at this time.

**Comment by matevz** [comment]
I fixed the tests by obtaining the block hash from HTTP client response directly instead of calling `.Hash()` function on go-ethereum's `Block` object. Feel free to close this issue.

**Comment by matevz** [comment]
FYI it seems that in commits on Nov 20 and Nov 21, calling `.Hash()` on go-ethereum's `Transaction` object also yields different hash than just fetching the one from `eth_getTransactionByHash` response.

**Comment by ptrus** [comment]
This won't be fixed at this time
