### ISSUE TITLE
Implement `eth_subscribe` and `eth_unsubscribe` methods on the webscoket endpoint

### ISSUE THREAD

**Issue by ptrus** [oasisprotocol/oasis-web3-gateway#75]
Documentation:
- https://openethereum.github.io/JSONRPC-eth_pubsub-module
- https://infura.io/docs/ethereum/wss/introduction
- https://web3js.readthedocs.io/en/v1.2.7/web3-eth-subscribe.html

This enables clients to subscribe on various events in the websocket endpoint.

**Comment by anonymousGiga** [comment]
We have made a simple design as follows:
1. Add a processing function in the web socket to call this function when a subscription request is received. In this function, start a collaborative process and channel to listen the corresponding subscription event, and add the channel to event_bus at the same time.

   The code for collaborative process just like this:

   ```
   go func(xx chan <-)  {
   	for {
   		event <- xxchan：              
   			//Send the corresponding message back to the client through the web socket
   		case <-unsubscribed:
   			//unsubscribe, close
   		}
   	}
   ```

2. Add event bus, which accept all events from indexer when a new block indexed. After the event bus receives the event, it distributes the corresponding event to the subscribed channel.
3. After listening to the events in the corresponding channel, the coroutine in the first step sends the results to the client through the web socket.
![设计](https://user-images.githubusercontent.com/43949039/142752031-8a03ff01-029b-4151-9018-0e0f7045195b.PNG)

**Comment by kostko** [comment]
Yes, something like this makes sense on a high level. For the event bus you can use the one from Oasis Core (see https://github.com/oasisprotocol/oasis-core/tree/master/go/common/pubsub) to avoid any new dependencies.
