### ISSUE TITLE
If the return value does not exist, can null be changed to "" or [] to adapt to the rust interface?

### ISSUE THREAD

**Issue by cherideal** [oasisprotocol/oasis-web3-gateway#77]
{
	"jsonrpc":"2.0",
	"method":"eth_getLogs",
	"params":[
		{ "fromBlock": "0x200", "toBlock" : "0x205"}
	],
	"id":3
}
--------------------------------------
{
    "jsonrpc": "2.0",
    "id": 3,
    "result": null --> []
}

**Comment by cherideal** [comment]
"accessList": null, => "accessList": "",

**Comment by ptrus** [comment]
Can you check what other gateways (e.g `Infura` or `geth`) return in this situation? 

For example in `eth_getTransactionReceipt` explicit `null` (and not "") is also returned by Infura: https://github.com/starfishlabs/oasis-evm-web3-gateway/pull/53

Ideally the gateway responses would match what majority of existing ETH tools expect and return.

**Comment by ptrus** [comment]
Reopen if other ETH tools/gateways treat `null`'s differently than the oasis-evm-web3-gateway.
