### ISSUE TITLE
Some transaction logs seem to be missing

### ISSUE THREAD

**Issue by cherideal** [oasisprotocol/oasis-web3-gateway#79]
Some transaction logs seem to be missing. I deployed the uniswap contract on emerald, and then called addLiquidityETH on emerald and ropsten at the same time, and found that the eth_log on emerald was incomplete.
https://ropsten.etherscan.io/tx/0x7f412ea098ca90e5440ba927cfa0e1096d2048e630baa9a542c4ee315274c1ad
https://explorer-testnet.hybridx.exchange/tx/0xed0ac0dcaf134ef0ae266f522acfa3afae5038b2ac9b5e5c22a4136365a0a260/logs
[eth_getTransactionReceipt_emerald.txt](https://github.com/starfishlabs/oasis-evm-web3-gateway/files/7606868/eth_getTransactionReceipt_emerald.txt)
[eth_getTransactionReceipt_ropsten.txt](https://github.com/starfishlabs/oasis-evm-web3-gateway/files/7606869/eth_getTransactionReceipt_ropsten.txt)

**Comment by ptrus** [comment]
This is indeed the case, currently only the last emitted event will ever get through to the web3-gateway due to a bug in the paratime sdk. Upstream tracking PR with the fix: https://github.com/oasisprotocol/oasis-sdk/pull/675
