### ISSUE TITLE
GetTransactionCount ignores the `blockNum` parameter

### ISSUE THREAD

**Issue by ptrus** [oasisprotocol/oasis-web3-gateway#8]
`GetTransactionCount` will currently always return the latest nonce for the account, ignoring the `blockNum` parameter:
https://github.com/starfishlabs/oasis-evm-web3-gateway/blob/825d855ab35ce813f744dab66cd78021fe1cb84c/rpc/eth/api.go#L215

**Comment by pro-wh** [comment]
looks like several of the methods always use latest

**Comment by pro-wh** [comment]
actually let's open new issues for those if they end up causing problems
