### ISSUE TITLE
The transaction hash does not match the block hash.

### ISSUE THREAD

**Issue by cherideal** [oasisprotocol/oasis-web3-gateway#80]
eth_getBlockByHash: 
`{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "difficulty": "0x0",
        "extraData": "0x",
        "gasLimit": "0x1406f40",
        "gasUsed": "0x1e8480",
        "hash": "**0x8c579c8fcc6c118b1e8abc17f4514f9ab498370bb7a485dfe86d3b5eefa06f37**",
        "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "miner": "0x0000000000000000000000000000000088888888",
        "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "nonce": "0x0000000000000000",
        "number": "0x12ae",
        "parentHash": "0x6221c1cd3d95ca823b0dfd86201de0279b6073d98973975295c540555467f624",
        "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
        "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
        "size": "0x64",
        "stateRoot": "0x8320380074ce8f5f26d1737be6123e43f583cd821e5530e2587e52767c0ad154",
        "timestamp": "0x619cfb8a",
        "totalDifficulty": "0x0",
        "transactions": [
            "**0xb2056584dba960571e6d8210d4d5ef8d8789c50685799412c60bc738741eb452**"
        ],
        "transactionsRoot": "0x988d9b4105158fbfb77f15d2454ac3b77336c5b0a69bc9a7a6ba3bf86c062932",
        "uncles": []
    }
}
`
eth_getTransactionByHash
`
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "blockHash": "**0x06d07bf847ad8cf74c28a28b474832f221e6c917cd4c0b89b1df5d8a7a2e53d1**",
        "blockNumber": "0x12ac",
        "from": "0x79a73a787dad8fadc32c51428d0b068380e921f2",
        "gas": "0x1e8480",
        "gasPrice": "0x3b9aca00",
        "maxFeePerGas": "0x0",
        "maxPriorityFeePerGas": "0x0",
        "hash": "**0xb2056584dba960571e6d8210d4d5ef8d8789c50685799412c60bc738741eb452**",
        "input": "0x418d78d4000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000001c0000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002c00000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000003424e420000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000345544800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004524f53450000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000008a9a869c80000000000000000000000000000000000000000000000000000003d74572bf80000000000000000000000000000000000000000000000000000000001a0f021b000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000619cfb0500000000000000000000000000000000000000000000000000000000619cfb1600000000000000000000000000000000000000000000000000000000619cfb07000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000001c0d8a00000000000000000000000000000000000000000000000000000000001c0d9300000000000000000000000000000000000000000000000000000000001c0d8d",
        "nonce": "0x396",
        "to": "0xaf4db1f08d6226ae58d7ca1596f4e0b9d28bb7ae",
        "transactionIndex": "0x0",
        "value": "0x0",
        "type": "0x0",
        "accessList": null,
        "chainId": "0x0",
        "v": "0x14a4e",
        "r": "0xe99a1e544d9c4f393e439d400751c96f31852dd220a8ab6967c11006008b4677",
        "s": "0x381d6774e3fa55255b85afdac24a286ca182588ad8e24a4bb816b3fb47f4dc15"
    }
}
`

**Comment by ptrus** [comment]
Hey i think this should already be fixed a while ago by https://github.com/starfishlabs/oasis-evm-web3-gateway/issues/56

Can you confirm this is still an issue?

Test on Emerald staging today:
```bash
// eth_getBlockByHash
curl https://testnet.emerald.oasis.dev \                          
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_getBlockByHash", "params": ["0x5297a215ee8d4ab1bcecf1da37a9a733be1aa552f65313d9ed382a65b72955a2", false],"id":1}'
                                                                                                                                      
{"jsonrpc":"2.0","id":1,"result":{"difficulty":"0x0","extraData":"0x","gasLimit":"0x1406f40","gasUsed":"0x1e8480","hash":"0x5297a215ee8d4ab1bcecf1da37a9a733be1aa552f65313d9ed382a65b72955a2","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000010000000000002000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000","miner":"0x0000000000000000000000000000000088888888","mixHash":"0x0000000000000000000000000000000000000000000000000000000000000000","nonce":"0x0000000000000000","number":"0x1931","parentHash":"0x9d3ce49ecbc3bfec1e3f9dab0c71f25da40d784047fa41f8e500a3320d7eb71a","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x64","stateRoot":"0x1cb3ef4171839e47641afb97601c482f311a7d051a86392a7615223fdccee272","timestamp":"0x61a4c2f7","totalDifficulty":"0x0","transactions":["0x52a1f29cfbbd078b670f0be789e48dd3581adee6d89022bbe06f15a8c19ed72b"],"transactionsRoot":"0x083c8ad66a4f1e190a5bb353333b81fa2e7cd81b17c228b1956d3ba003f67988","uncles":[]}}

// eth_getTransactionByHash
curl https://testnet.emerald.oasis.dev \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_getTransactionByHash", "params": ["0x52a1f29cfbbd078b670f0be789e48dd3581adee6d89022bbe06f15a8c19ed72b"],"id":1}' 
                                                                                                                                                        
{"jsonrpc":"2.0","id":1,"result":{"blockHash":"0x5297a215ee8d4ab1bcecf1da37a9a733be1aa552f65313d9ed382a65b72955a2","blockNumber":"0x1931","from":"0x79a73a787dad8fadc32c51428d0b068380e921f2","gas":"0x1e8480","gasPrice":"0x3b9aca00","maxFeePerGas":"0x0","maxPriorityFeePerGas":"0x0","hash":"0x52a1f29cfbbd078b670f0be789e48dd3581adee6d89022bbe06f15a8c19ed72b","input":"0x418d78d4000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000002e000000000000000000000000000000000000000000000000000000000000003c000000000000000000000000000000000000000000000000000000000000004a0000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001c000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000003424e4200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003455448000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000045553444300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000455534454000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004524f5345000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003534f4c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000008ef4689290000000000000000000000000000000000000000000000000000003ea4e15b0f8000000000000000000000000000000000000000000000000000000003b9ac80c000000000000000000000000000000000000000000000000000000003ba9c01300000000000000000000000000000000000000000000000000000000124c7b940000000000000000000000000000000000000000000000000000002f74caa32000000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000061a4c2980000000000000000000000000000000000000000000000000000000061a4c2ba0000000000000000000000000000000000000000000000000000000061a4c28b0000000000000000000000000000000000000000000000000000000061a4c28b0000000000000000000000000000000000000000000000000000000061a4c2880000000000000000000000000000000000000000000000000000000061a4c269000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000001eee7100000000000000000000000000000000000000000000000000000000001eee7800000000000000000000000000000000000000000000000000000000001eee6a00000000000000000000000000000000000000000000000000000000001eee6a00000000000000000000000000000000000000000000000000000000001eee6700000000000000000000000000000000000000000000000000000000001eee5a","nonce":"0x6a5","to":"0xaf4db1f08d6226ae58d7ca1596f4e0b9d28bb7ae","transactionIndex":"0x0","value":"0x0","type":"0x0","accessList":null,"chainId":"0x0","v":"0x14a4d","r":"0x30a32b5f79bde692a61c48f62d2dc7333b692c222c9e70f6af23451e884c5ae3","s":"0x676da7bf7ee36803c464da3d05e2810a8729d1037513621e17e3304d968c1a04"}}
```

The `hash` in `eth_getBlockByHash` matches the `blockHash` in `eth_getTransactionByHash`: `0x5297a215ee8d4ab1bcecf1da37a9a733be1aa552f65313d9ed382a65b72955a2`

**Comment by ptrus** [comment]
Feel free to reopen if this is not fixed.

**Comment by cherideal** [comment]
This problem still exists, maybe you should confirm if this is a proble first.
the block 0x8c579c8fcc6c118b1e8abc17f4514f9ab498370bb7a485dfe86d3b5eefa06f37 contains a transaction: 0xb2056584dba960571e6d8210d4d5ef8d8789c50685799412c60bc738741eb452
but transaction 0xb2056584dba960571e6d8210d4d5ef8d8789c50685799412c60bc738741eb452's block hash is: 0x06d07bf847ad8cf74c28a28b474832f221e6c917cd4c0b89b1df5d8a7a2e53d1

**Comment by ptrus** [comment]
Hm yeah it is indeed an issue for that block. Let me double-check, the gateway might just need a reindexing.

**Comment by ptrus** [comment]
I checked for that specific case and it is fixed in latest code. The gateway just needs reindexing should be fixed soon. Thanks for the report!
