### ISSUE TITLE
Health check endpoint

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-web3-gateway#86]
There should be a health check endpoint that can be reached via an HTTP GET request. It should report the health status of the gateway by performing some standard queries against the latest round (could be done periodically in a background goroutine so that health check requests don't cause too much load).

This would help for things like load balancers which currently rely just on TCP connection establishment to know whether the gateway is available.

**Comment by ptrus** [comment]
I think a goroutine that periodically (e.g. every 30 secs) does:
- query oasis-node status (ensure that is has finished initial syncing?)
- query db for latest indexed round
- query node for latest round
- compare rounds (ensure these are not too far apart)

would make sense.

This tests:
- oasis-node is up
- gateway is up
- db is up and working
- node is up and working
- both were updated at the same time

**Comment by kostko** [comment]
Sounds like a good plan.
