### ISSUE TITLE
Add more database indexes where needed

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-web3-gateway#96]
All the database models and queries should be reviewed and appropriate indexes added where needed. One such example is the `blocks` table which seems to lack an index on `round` even though there are many round-related queries.

**Comment by ptrus** [comment]
Should be done after https://github.com/starfishlabs/oasis-evm-web3-gateway/pull/74 in case switching the library changes the way the db is initialized

**Comment by ptrus** [comment]
Obvious ones that are missing

Transactions:
- on `block_hash`
- on `round` 

Blocks:
- on `round`

Logs:
- on `round`
- on `block_hash`
